In [1]:
import scipy.io
import numpy as np
helperOC_brt = scipy.io.loadmat('helperoc_air3d.mat')['data']
odp_brt = np.load('odp_air3d.npy')
print(helperOC_brt.shape)
print(odp_brt.shape)

(11, 11, 21, 11)
(11, 11, 21)


In [2]:
helperOC_brt[..., -1]

array([[[1.16421356, 1.16421356, 1.16421356, ..., 1.16421356,
         1.16421356, 1.16421356],
        [1.03062485, 1.03062485, 1.03062485, ..., 1.03062485,
         1.03062485, 1.03062485],
        [0.91619038, 0.91619038, 0.91619038, ..., 0.91619038,
         0.91619038, 0.91619038],
        ...,
        [0.91619038, 0.91619038, 0.91619038, ..., 0.91619038,
         0.91619038, 0.91619038],
        [1.03062485, 1.03062485, 1.03062485, ..., 1.03062485,
         1.03062485, 1.03062485],
        [1.16421356, 1.16421356, 1.16421356, ..., 1.16421356,
         1.16421356, 1.16421356]],

       [[1.03062485, 1.03062485, 1.03062485, ..., 1.03062485,
         1.03062485, 1.03062485],
        [0.88137085, 0.88137085, 0.88137085, ..., 0.88137085,
         0.88137085, 0.88137085],
        [0.75      , 0.75      , 0.75      , ..., 0.75      ,
         0.75      , 0.75      ],
        ...,
        [0.75      , 0.75      , 0.75      , ..., 0.75      ,
         0.75      , 0.75      ],
        [0.8

In [3]:
odp_brt

array([[[1.1642135 , 1.1642135 , 1.1642135 , ..., 1.1642135 ,
         1.1642135 , 1.1642135 ],
        [1.0306249 , 1.0306249 , 1.0306249 , ..., 1.0306249 ,
         1.0306249 , 1.0306249 ],
        [0.9161904 , 0.9161904 , 0.9161904 , ..., 0.9161904 ,
         0.9161904 , 0.9161904 ],
        ...,
        [0.9161904 , 0.9161904 , 0.9161904 , ..., 0.9161904 ,
         0.9161904 , 0.9161904 ],
        [1.0306249 , 1.0306249 , 1.0306249 , ..., 1.0306249 ,
         1.0306249 , 1.0306249 ],
        [1.1642135 , 1.1642135 , 1.1642135 , ..., 1.1642135 ,
         1.1642135 , 1.1642135 ]],

       [[1.0306249 , 1.0306249 , 1.0306249 , ..., 1.0306249 ,
         1.0306249 , 1.0306249 ],
        [0.88137084, 0.88137084, 0.88137084, ..., 0.88137084,
         0.88137084, 0.88137084],
        [0.75      , 0.75      , 0.75      , ..., 0.75      ,
         0.75      , 0.75      ],
        ...,
        [0.75      , 0.75      , 0.75      , ..., 0.75      ,
         0.75      , 0.75      ],
        [0.8

In [4]:
((odp_brt - helperOC_brt[..., -1])**2).mean()

0.002150280602627688

In [9]:
from brt import g
from atu.utils import spa_deriv
from brt import car_brt

In [14]:
x = np.array([1, 0, -np.pi/2])
index = g.get_index(x)
print(g.get_value(odp_brt, x))
deriv = spa_deriv(index, odp_brt, g)
u = car_brt.opt_ctrl_non_hcl(x, deriv)
d = car_brt.opt_dstb_non_hcl(deriv)
print(u ,d)

0.4519777
[1.] [-1.]


In [13]:
deriv

array([ 0.73990606, -0.54852352,  0.31247569])